AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Hub VPC with Transit Gateway and external RAM sharing.
  Spoke VPCs will attach separately.

Parameters:
  EnvironmentName:
    Type: String
    Default: Hub

  HubVpcCIDR:
    Type: String
    Default: 10.0.0.0/16

  HubPublicSubnetCIDR:
    Type: String
    Default: 10.0.1.0/24

  HubPrivateSubnetCIDR:
    Type: String
    Default: 10.0.2.0/24

Resources:

  #################################################
  # HUB VPC
  #################################################
  HubVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref HubVpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  #################################################
  # Internet Gateway
  #################################################
  HubIGW:
    Type: AWS::EC2::InternetGateway

  HubIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HubVPC
      InternetGatewayId: !Ref HubIGW

  #################################################
  # Subnets
  #################################################
  HubPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HubVPC
      CidrBlock: !Ref HubPublicSubnetCIDR
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Public-Subnet

  HubPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HubVPC
      CidrBlock: !Ref HubPrivateSubnetCIDR
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Private-Subnet

  #################################################
  # Route Tables
  #################################################
  HubPublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HubVPC

  HubPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: HubIGWAttachment
    Properties:
      RouteTableId: !Ref HubPublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref HubIGW

  HubPublicRTAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref HubPublicSubnet
      RouteTableId: !Ref HubPublicRT

  HubPrivateRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HubVPC

  HubPrivateRTAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref HubPrivateSubnet
      RouteTableId: !Ref HubPrivateRT

  #################################################
  # TRANSIT GATEWAY
  #################################################
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: disable
      DefaultRouteTablePropagation: disable
      DnsSupport: enable
      VpnEcmpSupport: enable
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TGW

  #################################################
  # TGW ROUTE TABLE
  #################################################
  TGWRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TGW-RT

  #################################################
  # HUB VPC ATTACHMENT
  #################################################
  HubTGWAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref HubVPC
      SubnetIds:
        - !Ref HubPrivateSubnet
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Hub-Attachment

  #################################################
  # TGW ASSOCIATION & PROPAGATION
  #################################################
  HubTGWAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref HubTGWAttachment
      TransitGatewayRouteTableId: !Ref TGWRouteTable

  HubTGWPropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref HubTGWAttachment
      TransitGatewayRouteTableId: !Ref TGWRouteTable

  #################################################
  # HUB ROUTE TO TGW
  #################################################
  HubPrivateRouteToTGW:
    Type: AWS::EC2::Route
    DependsOn: HubTGWAttachment
    Properties:
      RouteTableId: !Ref HubPrivateRT
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: !Ref TransitGateway

  #################################################
  # RAM SHARING (EXTERNAL SPOKE ACCOUNTS)
  #################################################
  TGWRAMShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: TGW-External-Share
      AllowExternalPrincipals: true
      Principals:
        - '417371242369'
        - '414329322210'
      ResourceArns:
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${TransitGateway}

Outputs:
  HubVpcId:
    Description: Hub VPC ID
    Value: !Ref HubVPC

  TransitGatewayId:
    Description: Transit Gateway ID
    Value: !Ref TransitGateway

  TGWRouteTableId:
    Description: Transit Gateway Route Table ID
    Value: !Ref TGWRouteTable
